<?php
declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

final class ApiError extends RuntimeException { public int $status; public function __construct(string $message, int $status = 400){ parent::__construct($message); $this->status=$status; } }
function out(array $data, int $status=200): never { http_response_code($status); echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function fail(Throwable $e): never { out(['error'=>$e->getMessage()], $e instanceof ApiError ? $e->status : 500); }
function body(): array { $raw=file_get_contents('php://input'); $data=json_decode($raw ?: '{}', true); return is_array($data)?$data:[]; }
function root(): string { $path=__DIR__.'/runtime-data'; if(!is_dir($path)) @mkdir($path,0777,true); if(!is_writable($path)) throw new ApiError('De sessie-opslag is niet schrijfbaar.',500); return $path; }
function code(string $id): string { return substr(hash('sha256',$id),0,20); }
function path(string $code): string { return root().'/'.$code.'.json'; }
function lock(string $code): string { return root().'/'.$code.'.lock'; }
function readSession(string $code): ?array { $p=path($code); if(!is_file($p)) return null; $v=json_decode((string)file_get_contents($p),true); return is_array($v)?$v:null; }
function saveSession(array $s): void { file_put_contents(path((string)$s['code']), json_encode($s,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL, LOCK_EX); }
function locked(string $code, callable $fn): array { $h=fopen(lock($code),'c+'); if(!$h) throw new ApiError('Sessie kan niet worden vergrendeld.',500); flock($h,LOCK_EX); try{$s=readSession($code); $s=$fn($s); if($s!==null) saveSession($s); return $s;}finally{flock($h,LOCK_UN);fclose($h);} }
function now(): int { return (int)round(microtime(true)*1000); }
function token(): string { return bin2hex(random_bytes(16)); }
function cleanName(mixed $v): string { $v=trim((string)$v); if($v==='') throw new ApiError('Vul een naam in.'); return mb_substr($v,0,60); }
function icon(int $n): string { $icons=['🦊','🐸','🦄','🐼','🦁','🐙','🐝','🐨','🦖','🐳','🦩','🐢']; return $icons[$n%count($icons)]; }
function normalize(array $s): array {
  $t=now();
  if(($s['phase']??'')==='research' && $t >= (int)$s['roundEndsAt']) { $s['phase']='between'; $s['transitionEndsAt']=$t+5000; }
  if(($s['phase']??'')==='between' && $t >= (int)$s['transitionEndsAt']) { $s['currentRound']++; if($s['currentRound'] >= $s['config']['aantalWoordenPerStudent']) { $s['phase']='presentations'; $s['currentRound']=$s['config']['aantalWoordenPerStudent']-1; } else { $s['phase']='research'; $s['roundEndsAt']=$t+$s['config']['onderzoektijdPerWoordInSeconden']*1000; } }
  if(($s['phase']??'')==='presentations' && is_array($s['presentation']??null) && ($s['presentation']['startedAt']??null)!==null && $t >= (int)$s['presentation']['endsAt']) { finishPresentation($s); }
  return $s;
}
function finishPresentation(array &$s): void { $p=$s['presentation']??null; if(!$p) return; $score=max(0,(int)($p['endsAt']??now())-(int)($p['startedAt']??now())); $seconds=(int)floor($score/1000); foreach(($p['studentIds']??[]) as $id){$s['scores'][$id]=max((int)($s['scores'][$id]??0),$seconds);}$s['presented'][]=['word'=>$p['word']??'','studentIds'=>$p['studentIds']??[]]; $s['presentation']=null; }
function assignWords(array &$s, array &$p, bool $late=false): void { $rounds=(int)$s['config']['aantalWoordenPerStudent']; $all=$s['config']['jargonWoorden']; $p['words']=array_fill(0,$rounds,null); $start=0; if($late){$start=($s['phase']??'')==='between'?(int)$s['currentRound']+1:(($s['phase']??'')==='presentations'?$rounds:max(0,(int)$s['currentRound']));} $used=[]; foreach($s['participants'] as $other) foreach(($other['words']??[]) as $w) if($w!==null) $used[$w]=true; $pool=array_values(array_filter($all,fn($w)=>!isset($used[$w]))); if(count($pool)<$rounds-$start)$pool=$all; if($rounds>$start){shuffle($pool);for($i=$start;$i<$rounds;$i++){$p['words'][$i]=$pool[($i-$start)%count($pool)];}} }
function pub(array $s, ?string $participantToken=null): array {
  $s=normalize($s); $participants=array_map(fn($p)=>['id'=>$p['id'],'name'=>$p['name'],'icon'=>$p['icon'],'joinedAt'=>$p['joinedAt'],'nameRequest'=>$p['nameRequest']??null],$s['participants']);
  $p=null; foreach($s['participants'] as $x) if($participantToken && hash_equals((string)$x['token'],(string)$participantToken)){$p=$x;break;}
  $active=$s['presentation']; $remaining=0; if($active && $active['startedAt']!==null)$remaining=max(0,(int)ceil(((int)$active['endsAt']-now())/1000));
  $scores=[]; foreach($s['scores'] as $id=>$seconds){foreach($s['participants'] as $x)if($x['id']===$id)$scores[]=['name'=>$x['name'],'icon'=>$x['icon'],'seconds'=>(int)$seconds];} usort($scores,fn($a,$b)=>$b['seconds']<=>$a['seconds']);
  return ['code'=>$s['code'],'phase'=>$s['phase'],'started'=>$s['started'],'currentRound'=>$s['currentRound'],'roundEndsAt'=>$s['roundEndsAt'],'transitionEndsAt'=>$s['transitionEndsAt'],'config'=>$s['config'],'participants'=>$participants,'words'=>$s['config']['jargonWoorden'],'myWords'=>$p['words']??null,'myId'=>$p['id']??null,'myName'=>$p['name']??null,'myVote'=>($active&&$p&&isset($active['votes'][$p['id']]))?$active['votes'][$p['id']]:null,'presentation'=>$active?['studentIds'=>$active['studentIds'],'studentNames'=>$active['studentNames'],'word'=>$active['word'],'spinning'=>$active['spinning'],'spinNonce'=>$active['spinNonce'],'startedAt'=>$active['startedAt'],'remainingSeconds'=>$remaining,'up'=>count(array_filter($active['votes'],fn($v)=>$v==='up')),'down'=>count(array_filter($active['votes'],fn($v)=>$v==='down'))]:null,'scores'=>$scores,'showScore'=>(bool)($s['showScore']??false),'finished'=>$s['phase']==='finished'];
}
try {
  $method=$_SERVER['REQUEST_METHOD']??'GET'; $action=$_GET['action']??'state'; $unique=trim((string)($_GET['unique_id']??'')); if($unique==='')throw new ApiError('unique_id ontbreekt.'); $c=code($unique); $input=$method==='POST'?body():[]; $s=readSession($c);
  if($action==='init') { if(!$s){$cfg=$input['config']??[]; $words=[]; foreach(($cfg['jargonWoorden']??[]) as $w){$w=trim((string)$w);if($w!==''&&!in_array($w,$words,true))$words[]=$w;} if(!$words)throw new ApiError('Voeg minimaal één jargonwoord toe.'); $s=['code'=>$c,'uniqueId'=>$unique,'createdAt'=>now(),'teacherToken'=>null,'config'=>['aantalWoordenPerStudent'=>max(1,(int)($cfg['aantalWoordenPerStudent']??3)),'onderzoektijdPerWoordInSeconden'=>max(5,(int)($cfg['onderzoektijdPerWoordInSeconden']??120)),'spreektijdInSeconden'=>max(5,(int)($cfg['spreektijdInSeconden']??60)),'jargonWoorden'=>$words],'participants'=>[],'scores'=>[],'presented'=>[],'showScore'=>false,'started'=>false,'phase'=>'lobby','currentRound'=>-1,'roundEndsAt'=>0,'transitionEndsAt'=>0,'presentation'=>null]; saveSession($s); } }
  if(!$s) throw new ApiError('De docent heeft deze activiteit nog niet gestart.',404);
  $s=locked($c,function($s)use($action,$input){$s=normalize($s);$t=now();
    if($action==='claim_teacher'){ $given=(string)($input['teacherToken']??''); if($s['teacherToken']===null){$s['teacherToken']=$given!==''?$given:token();} elseif(!hash_equals((string)$s['teacherToken'],$given))throw new ApiError('De docentrol is al bezet.',409); return $s; }
    if($action==='join'){ $pt=(string)($input['participantToken']??''); $name=cleanName($input['name']??''); foreach($s['participants'] as &$p)if($pt!==''&&hash_equals($p['token'],$pt)){$p['name']=$name;return $s;} $p=['id'=>token(),'token'=>$pt!==''?$pt:token(),'name'=>$name,'icon'=>icon(count($s['participants'])),'joinedAt'=>$t,'words'=>[]]; assignWords($s,$p,$s['started']);$s['participants'][]=$p;return $s; }
    if($action==='rename_request'){ $pt=(string)($input['participantToken']??''); foreach($s['participants'] as &$p)if(hash_equals($p['token'],$pt)){$p['nameRequest']=cleanName($input['name']??'');return $s;} throw new ApiError('Student niet gevonden.',404); }
    $teacher=(string)($input['teacherToken']??''); if(in_array($action,['start','restart','restart_presentations','next_research','spin_student','spin_word','start_time','show_score','finish'],true)&&!$s['teacherToken']||in_array($action,['start','restart','restart_presentations','next_research','spin_student','spin_word','start_time','show_score','finish'],true)&&!hash_equals((string)$s['teacherToken'],$teacher))throw new ApiError('Alleen de docent mag dit doen.',403);
    if($action==='approve_name'){ $id=(string)($input['participantId']??''); foreach($s['participants'] as &$p)if($p['id']===$id){if(!empty($p['nameRequest'])){$p['name']=$p['nameRequest'];$p['nameRequest']=null;}return $s;} throw new ApiError('Student niet gevonden.',404); }
    if($action==='show_score'){$s['showScore']=true;return $s;}
    if($action==='start'||$action==='restart'){ if($action==='restart'){$s['participants']=array_map(function($p)use(&$s){assignWords($s,$p,false);return $p;},$s['participants']);$s['scores']=[];$s['presented']=[];} $s['showScore']=false;$s['started']=true;$s['phase']='research';$s['currentRound']=0;$s['roundEndsAt']=$t+$s['config']['onderzoektijdPerWoordInSeconden']*1000;$s['transitionEndsAt']=0;$s['presentation']=null;return $s; }
    if($action==='next_research'){if(!$s['started']||!in_array($s['phase'],['research','between'],true))throw new ApiError('Er is geen actieve onderzoeksronde.');$s['currentRound']++;if($s['currentRound'] >= $s['config']['aantalWoordenPerStudent']){$s['phase']='presentations';$s['currentRound']=$s['config']['aantalWoordenPerStudent']-1;$s['presentation']=null;}else{$s['phase']='research';$s['roundEndsAt']=$t+$s['config']['onderzoektijdPerWoordInSeconden']*1000;$s['transitionEndsAt']=0;}return $s;}
    if($action==='restart_presentations'){if(!$s['started'])throw new ApiError('Start eerst de activiteit.');$s['showScore']=false;$s['phase']='presentations';$s['currentRound']=$s['config']['aantalWoordenPerStudent']-1;$s['presentation']=null;$s['presented']=[];$s['scores']=[];return $s;}
    if($action==='spin_student'||$action==='spin_word'){ $p=$s['presentation']??['studentIds'=>[],'studentNames'=>[],'word'=>null,'spinning'=>false,'spinNonce'=>0,'startedAt'=>null,'endsAt'=>0,'baseSeconds'=>$s['config']['spreektijdInSeconden'],'adjustment'=>0,'votes'=>[]]; if($action==='spin_student'){ $n=max(1,min(3,(int)($input['count']??1)));$available=array_values(array_filter($s['participants'],fn($x)=>!empty($x['words'])));shuffle($available);$chosen=array_slice($available,0,$n);$p['studentIds']=array_column($chosen,'id');$p['studentNames']=array_column($chosen,'name'); } else {$used=array_column($s['presented'],'word');$available=array_values(array_filter($s['config']['jargonWoorden'],fn($w)=>!in_array($w,$used,true)));$chosenWords=[];foreach($s['participants'] as $student)if(in_array($student['id'],$p['studentIds']??[],true))foreach(($student['words']??[]) as $w)if($w!==null&&!in_array($w,$used,true))$chosenWords[]=$w;$available=$chosenWords?:$available;$p['word']=$available[array_rand($available?:$s['config']['jargonWoorden'])];}$p['spinning']=true;$p['spinNonce']=(int)($p['spinNonce']??0)+1;$p['startedAt']=null;$p['endsAt']=0;$p['adjustment']=0;$p['votes']=[];$s['presentation']=$p;return $s; }
    if($action==='start_time'){if(!$s['presentation']||!$s['presentation']['word']||!$s['presentation']['studentIds'])throw new ApiError('Spin eerst een student en een woord.');$s['presentation']['spinning']=false;$s['presentation']['startedAt']=$t;$s['presentation']['endsAt']=$t+($s['config']['spreektijdInSeconden']*1000);return $s;}
    if($action==='vote'){ $pt=(string)($input['participantToken']??'');$vote=(string)($input['vote']??'');if(!in_array($vote,['up','down'],true)||!$s['presentation']||$s['presentation']['startedAt']===null)throw new ApiError('Stemmen kan nu niet.');$pid=null;foreach($s['participants'] as $p)if(hash_equals($p['token'],$pt))$pid=$p['id'];if(!$pid)throw new ApiError('Student niet gevonden.',404);if(isset($s['presentation']['votes'][$pid]))throw new ApiError('Je hebt al gestemd voor deze presentator.',409);$s['presentation']['votes'][$pid]=$vote;$delta=$vote==='up'?5:-5;$s['presentation']['endsAt']=max($t+1000,$s['presentation']['endsAt']+$delta*1000);return $s; }
    if($action==='finish'){$s['phase']='finished';$s['started']=false;$s['presentation']=null;return $s;} return $s;
  });
  $pt=(string)($_GET['participantToken']??''); $response=pub($s,$pt); if($action==='claim_teacher')$response['teacherToken']=$s['teacherToken']; out($response);
} catch(Throwable $e){fail($e);}
