(() => {
  const q = new URLSearchParams(location.search);
  // Courses geeft deze contextparameters mee. `role` blijft tijdelijk ondersteund voor oude demo-URL's.
  const view = q.get('canvas_course_view') || q.get('role') || 'student';
  const courseMode = q.get('canvas_course_mode') || 'individual';
  const uniqueId = q.get('unique_id') || q.get('key') || '';
  const dataUrl = q.get('data') || '';
  const api = `api.php?unique_id=${encodeURIComponent(uniqueId)}`;
  const app = document.getElementById('app');
  const nameKey = `jargonwoorden-presenteren:naam:${uniqueId}`;
  const tokenKey = `jargonwoorden-presenteren:student-token:${uniqueId}`;
  const teacherKey = `jargonwoorden-presenteren:docent-token:${uniqueId}`;
  let config = null, state = null, name = localStorage.getItem(nameKey) || '', participantToken = localStorage.getItem(tokenKey) || '', teacherToken = localStorage.getItem(teacherKey) || '';
  let pollTimer = null, lastSpin = -1, toastTimer = null, previousPhase = null;
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const createParticipantToken = () => {
    if (window.crypto?.randomUUID) return window.crypto.randomUUID();
    if (window.crypto?.getRandomValues) {
      const bytes = new Uint32Array(4);
      window.crypto.getRandomValues(bytes);
      return Array.from(bytes, value => value.toString(16)).join('-');
    }
    return `student-${Date.now().toString(16)}-${Math.random().toString(16).slice(2)}`;
  };
  const post = async (action, data = {}) => { const r = await fetch(`${api}&action=${action}`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data)}); const j=await r.json(); if(!r.ok) throw Error(j.error || 'Er ging iets mis.'); return j; };
  const get = async () => { const r=await fetch(`${api}&action=state&participantToken=${encodeURIComponent(participantToken)}`,{cache:'no-store'}); const j=await r.json(); if(!r.ok) throw Error(j.error||'Sessie niet beschikbaar.'); return j; };
  const button = (label, action, cls='') => `<button class="btn ${cls}" data-action="${action}">${label}</button>`;
  const phaseLabel = () => ({research:'Onderzoeksfase',between:'Onderzoeksfase',presentations:'Spelfase: presentaties',finished:'Afgerond',lobby:'Klaarzetten'}[state?.phase] || 'Klaarzetten');
  const layout = (eyebrow, title, content) => `<div class="top"><div><div class="eyebrow">${eyebrow}</div><div class="brand">Jargon<span>woorden</span> 🎤</div><div class="muted">${esc(title)}</div><div class="pill">Fase: ${phaseLabel()}</div></div></div>${content}`;
  const format = s => {s=Math.max(0,Math.ceil(Number(s)||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
  const remainingResearch = () => state ? Math.max(0,Math.ceil(((state.roundEndsAt||0)-Date.now())/1000)) : 0;
  function renderNameForm(message='') { app.innerHTML=layout('','Wie staat er klaar?',`<section class="card" style="max-width:560px;margin:auto"><h2>Geef je naam door 👋</h2><p class="muted">Deze naam verschijnt op het presentatiescherm. Wijzigen kan alleen via de docent.</p><input class="input" id="nameInput" maxlength="60" placeholder="Bijvoorbeeld: Sam" value="${esc(name)}" autofocus />${message?`<p class="status">${esc(message)}</p>`:''}<div class="actions">${button('Aanmelden','join','primary')}</div></section>`); }
  async function join() { const input=document.getElementById('nameInput'); name=(input?.value||'').trim(); if(!name)return renderNameForm('Vul eerst je naam in.'); if(!participantToken)participantToken=createParticipantToken(); try{state=await post('join',{name,participantToken});name=state.myName||name;localStorage.setItem(nameKey,name);localStorage.setItem(tokenKey,participantToken);render();startPolling();}catch(e){renderNameForm(e.message);} }
  function teacherClaim() { return post('claim_teacher',{teacherToken}).then(s=>{state=s;teacherToken=teacherToken||s.teacherToken;localStorage.setItem(teacherKey,teacherToken);render();}); }
  function ring(seconds,total) { const pct=total?Math.max(0,Math.min(100,(1-seconds/total)*100)):0; return `<div class="timer" style="--progress:${pct}"><strong>${format(seconds)}</strong></div>`; }
  function studentsHtml() { return `<div class="student-list">${state.participants.length?state.participants.map(p=>`<div class="student-row"><span class="avatar">${p.icon}</span>${esc(p.name)}</div>`).join(''):'<p class="muted">Nog niemand aangemeld…</p>'}</div>`; }
  function scoreHtml(limit=5) { return `<div>${(state.scores||[]).slice(0,limit).map((x,i)=>`<div class="score-row"><span>${i+1}. ${x.icon} ${esc(x.name)}</span><strong>${x.seconds}s</strong></div>`).join('')||'<p class="muted">Nog geen scores.</p>'}</div>`; }
  const researchQuestions = '<ol class="prompt-list"><li>Wat is het?</li><li>Waar kom je het tegen?</li><li>Geef een voorbeeld.</li><li>Waarom is het belangrijk?</li><li>Leg het uit alsof je het aan iemand uitlegt die het woord nog nooit heeft gehoord.</li></ol>';
  function renderTeacher() { const r=state.phase==='research'||state.phase==='between'; const requests=state.participants.filter(p=>p.nameRequest); app.innerHTML=layout('Docentmodus',state.phase==='finished'?'Afgerond':'Bedien het spel',`<div class="grid"><section class="card"><h2>${state.phase==='lobby'?'Klaar om te starten':state.phase==='presentations'?'Presentaties!':'Onderzoeksronde '+(state.currentRound+1)}</h2><p class="muted">${state.participants.length} student(en) aangemeld · ${state.config.jargonWoorden.length} woorden</p>${r?ring(state.phase==='research'?remainingResearch():5,state.config.onderzoektijdPerWoordInSeconden):''}<div class="actions">${button('▶ Start','start','primary')}${button('↻ Herstart','restart')}${r?button('⏭ Volgende ronde','next_research','primary'):''}${state.started&&state.phase!=='lobby'?button('↻ Herstart zonder onderzoek','restart_presentations'):''}${state.phase==='presentations'?button('🎰 Spin student','spin_student','pink'):''}${state.phase==='presentations'?button('🎲 Spin woord','spin_word','pink'):''}${state.phase==='presentations'?`<select class="input" id="countSelect" style="width:auto;margin:0"><option value="1">1 presentator</option><option value="2">2 presentatoren</option><option value="3">3 presentatoren</option></select>`:''}${state.phase==='presentations'?button('⏱ Start de tijd','start_time','green'):''}${button('🏆 Score tonen','show_score')}${button('⏹ Afronden','finish')}</div>${state.presentation?`<hr><h3>${esc(state.presentation.word||'Woord nog niet gekozen')}</h3><p>${(state.presentation.studentNames||[]).map(esc).join(' & ')||'Student nog niet gekozen'}</p>`:''}</section><section class="card"><h2>Aangemeld</h2>${studentsHtml()}${requests.length?`<hr><h3>Naamverzoeken</h3>${requests.map(p=>`<div class="student-row"><span>${esc(p.name)} → ${esc(p.nameRequest)}</span>${button('Goedkeuren','approve_name')}</div>`).join('')}`:''}${state.showScore?`<hr><h3>Top 3</h3>${scoreHtml(3)}`:''}</section></div>`); }
  function renderStudent() { const registeredName=state.myName||name||'Nog niet geregistreerd', phase=state.phase, seconds=remainingResearch(), total=state.config.onderzoektijdPerWoordInSeconden, word=state.myWords?.[Math.max(0,state.currentRound)]||'Je volgende woord komt eraan'; let body=''; if(phase==='lobby')body=`<div class="waiting">${state.participants.length} spelers klaar…</div>`; else if(phase==='research')body=`<div class="eyebrow">Ronde ${state.currentRound+1} · ${esc(registeredName)}</div><div class="word">${esc(word)}</div>${ring(seconds,total)}<p class="prompt-intro">Gebruik deze vragen voor je onderzoek en presentatie:</p>${researchQuestions}`; else if(phase==='between'){const dots='.'.repeat((Math.floor(Date.now()/500)%4));const funny=['pfff','heel ff hoor','nog ff, serieus','de woorden zijn onderweg…'][Math.floor(Date.now()/1800)%4];body=`<div class="waiting">Wisselen${dots}<br><small>${funny}</small></div>${ring(seconds,5)}`;} else if(phase==='presentations'){const dots='.'.repeat((Math.floor(Date.now()/500)%4));const funny=['pfff','heel ff hoor','nog ff, serieus','bijna aan de beurt…'][Math.floor(Date.now()/1800)%4];body=`<div class="waiting">hold on${dots}<br><small>${funny}</small></div>${state.presentation?.startedAt?`<div class="word">${esc(state.presentation.word||'')}</div>${researchQuestions}<div class="actions">${state.myVote?`<span class="pill">Je hebt al gestemd</span>`:button('👍 Goed bezig','vote_up','green')}${state.myVote?'' : button('👎 Nog eens','vote_down')}</div>`:'<p class="muted">De docent kiest zo een presentator en woord.</p>'}`;} else body='<div class="waiting">Bedankt, klaar! 🎉</div>'; app.innerHTML=layout('','',`<div class="grid"><section class="card">${body}</section><section class="card"><p class="word" style="font-size:32px">${esc(registeredName)}</p><hr><h2>Mijn woorden</h2><div class="list">${(state.myWords||[]).filter(Boolean).map((w,i)=>`<span class="chip">${i+1}. ${esc(w)}</span>`).join('')||'<span class="muted">Nog niet verdeeld</span>'}</div><hr><button class="btn" data-action="change_name">Naam wijzigen</button><p class="muted">Vraag de docent als je naam aangepast moet worden.</p></section></div>`); }
  function renderPresentation() {
    if (state.phase === 'research' || state.phase === 'between') {
      const round = state.currentRound + 1;
      app.innerHTML = layout('Presentatiescherm', 'De klas onderzoekt', `<div class="grid"><section class="card"><h2>Onderzoeksronde ${round}</h2><div class="waiting">Onderzoek het woord op je scherm 🔎</div>${state.phase === 'research' ? ring(remainingResearch(), state.config.onderzoektijdPerWoordInSeconden) : ring(5, 5)}</section><section class="card"><h2>Woorden</h2><div class="list">${state.words.map(w=>`<span class="chip">${esc(w)}</span>`).join('')}</div><hr><h2>Studenten</h2>${studentsHtml()}</section></div>`);
      return;
    }
    const p=state.presentation;
    if(p&&p.spinNonce!==lastSpin){lastSpin=p.spinNonce;setTimeout(()=>{const el=document.getElementById('letterbar');if(el){el.textContent=(p.studentNames||[]).join(' & ')||p.word||'…';}},900);}
    app.innerHTML=layout('Presentatiescherm',state.phase==='presentations'?'Wie legt het uit?':'Wacht op de docent',`<div class="grid"><section class="card"><h2>De letterbalk</h2><div class="letterbar" id="letterbar">${p?(p.spinning?'... & misschien jij?':esc((p.studentNames||[]).join(' & ')||p.word||'Klaar voor de spin!')):'Klaar voor de spin!'}</div>${p?.word?`<div class="word" style="font-size:clamp(30px,5vw,60px)">${esc(p.word)}</div>`:''}${p?.startedAt?`${ring(p.remainingSeconds,state.config.spreektijdInSeconden)}<div class="votes"><span class="vote-up">👍 ${p.up}</span><span class="vote-down">👎 ${p.down}</span></div>`:'<p class="muted">De docent kiest straks een student en woord.</p>'}</section><section class="card"><h2>Woorden</h2><div class="list">${state.words.map(w=>`<span class="chip">${esc(w)}</span>`).join('')}</div><hr><h2>Studenten</h2>${studentsHtml()}<hr><h2>🏆 Top 5</h2>${scoreHtml(5)}</section></div>`);
  }
  function render() {
    if (!state) return;
    if (view === 'teacher') return renderTeacher();
    if (view === 'presentation') return renderPresentation();
    if (!state.myId || !state.myName) return renderNameForm();
    return renderStudent();
  }
  async function action(a) { try { let response; if(a==='join')return join(); if(a==='change_name'){const next=prompt('Welke nieuwe naam wil je aanvragen?',name);if(next&&next.trim())response=await post('rename_request',{name:next.trim(),participantToken});else return;} else if(a==='approve_name'){const row=document.querySelector('[data-action="approve_name"]');const pending=state.participants.find(p=>p.nameRequest);if(!pending)return;response=await post(a,{teacherToken,participantId:pending.id});} else if(a==='spin_student'){response=await post(a,{teacherToken,count:document.getElementById('countSelect')?.value||1});} else if(a.startsWith('vote_')){if(state.myVote)return;response=await post('vote',{participantToken,vote:a==='vote_up'?'up':'down'});showToast(a==='vote_up');} else {response=await post(a,{teacherToken});} state=response;render();}catch(e){alert(e.message);} }
  function showToast(up){clearTimeout(toastTimer);const d=document.createElement('div');d.className=`toast ${up?'up':'down'}`;d.textContent=up?'😄':'😢';document.body.appendChild(d);toastTimer=setTimeout(()=>d.remove(),2100);}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action);});
  function bell(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.25,c.currentTime+.03);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.6);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.65);}catch(_){}}
  async function tick(renderResult=true){try{const next=await get();if(previousPhase==='research'&&next.phase==='between')bell();previousPhase=next.phase;state=next;if(state.myName){name=state.myName;localStorage.setItem(nameKey,name);}if(renderResult)render();}catch(e){if(renderResult&&!state)app.innerHTML=layout('Live sessie',e.message,'<section class="card"><p>Open eerst de docentweergave om deze activiteit te starten.</p></section>');}}
  function startPolling(){if(!pollTimer)pollTimer=setInterval(tick,1000);}
  async function init(){if(!uniqueId||!dataUrl){app.innerHTML='<section class="card"><h2>Configuratie ontbreekt</h2><p>Gebruik unique_id en data in de URL.</p></section>';return;}try{if(view==='teacher'){config=await fetch(dataUrl,{cache:'no-store'}).then(r=>r.json());state=await post('init',{config});await teacherClaim();startPolling();}else if(view==='presentation'){await tick(true);startPolling();}else if(!name||!participantToken){renderNameForm();}else{await tick(false);if(!state?.myId||!state?.myName){renderNameForm();}else{render();startPolling();}}if(courseMode==='plenary')document.body.classList.add('is-plenary');}catch(e){app.innerHTML=`<section class="card"><h2>Oeps</h2><p>${esc(e.message)}</p></section>`;}}
  init();
})();
