(() => {
  const params = new URLSearchParams(location.search);
  const view = params.get('canvas_course_view') || params.get('role') || 'student';
  const uniqueId = params.get('unique_id') || params.get('key') || '';
  const dataUrl = params.get('data') || '';
  const api = `api.php?unique_id=${encodeURIComponent(uniqueId)}`;
  const app = document.querySelector('#app');
  const tokenKey = `poll-vote:participant:${uniqueId}`;
  const teacherKey = `poll-vote:teacher:${uniqueId}`;
  let participantToken = localStorage.getItem(tokenKey) || '';
  let teacherToken = localStorage.getItem(teacherKey) || '';
  let state = null;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const createToken = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const call = async (action, payload = {}) => { const response = await fetch(`${api}&action=${action}`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const json = await response.json(); if(!response.ok) throw Error(json.error || 'Er ging iets mis.'); return json; };
  const stateGet = async () => { const response = await fetch(`${api}&action=state&participantToken=${encodeURIComponent(participantToken)}`,{cache:'no-store'}); const json = await response.json(); if(!response.ok) throw Error(json.error || 'De poll is nog niet gestart.'); return json; };
  const shell = (label, content, cls='') => `<div class="${cls}"><header class="hero"><div><div class="eyebrow">${esc(label)}</div><h1>${esc(state?.config?.titel || 'Poll & vote')}</h1></div><span class="tag">${state ? `${state.questionIndex + 1} / ${state.questions.length}` : 'live'}</span></header>${content}</div>`;
  const question = () => state.questions[state.questionIndex];
  const bars = q => { const max = Math.max(1,...q.answers.map(answer => answer.count)); return `<div class="answers">${q.answers.map((answer,index) => `<div class="bar-row"><span>${esc(answer.short)}</span><div class="bar"><div class="fill" style="width:${answer.count / max * 100}%"></div></div><strong class="count">${answer.count}</strong></div>`).join('')}</div>`; };
  function renderStudentName(message='') { app.innerHTML = shell('Poll & vote', `<section class="card" style="max-width:600px;margin:auto"><h2>Wie stemt mee?</h2><p class="muted">Je naam helpt de docent om een stem te corrigeren of te verwijderen.</p><input id="name" class="input" maxlength="60" placeholder="Jouw naam" autofocus><p class="small muted">${esc(message)}</p><div class="actions"><button class="btn primary" data-action="join">Meedoen</button></div></section>`); }
  function renderStudent() { const q = question(), vote = state.myVotes?.[state.questionIndex]; app.innerHTML = shell('Jouw stem', `<section class="card"><p class="question">${esc(q.question)}</p>${vote === undefined ? `<div class="answers">${q.answers.map((answer,index) => `<button class="choice" data-action="vote" data-answer="${index}">${esc(answer.long)}</button>`).join('')}</div>` : `<div class="empty">Je stem is opgeslagen. Wacht op de volgende vraag.</div>`}<p class="muted small">${state.totalVotes} stem${state.totalVotes === 1 ? '' : 'men'} bij deze vraag</p></section>`); }
  function renderPresentation() { const q = question(), hasVotes = state.totalVotes > 0; app.innerHTML = shell('Presentatie', `<section class="card">${hasVotes ? `<p class="question">${esc(q.question)}</p>${bars(q)}<p class="muted">${state.totalVotes} stem${state.totalVotes === 1 ? '' : 'men'} uitgebracht</p>` : `<p class="question">${esc(q.question)}</p><div class="answers">${q.answers.map(answer => `<div class="answer">${esc(answer.long)}</div>`).join('')}</div><p class="muted">De uitslag verschijnt zodra de eerste persoon stemt.</p>`}</section>`, 'presentation'); }
  function renderTeacher() { const q = question(); app.innerHTML = shell('Docentinterface', `<div class="grid"><section class="card"><div class="nav"><button class="btn" data-action="previous">← Vorige</button><select class="select" id="questionSelect">${state.questions.map((item,index)=>`<option value="${index}" ${index===state.questionIndex?'selected':''}>Vraag ${index+1}: ${esc(item.question)}</option>`).join('')}</select><button class="btn" data-action="next">Volgende →</button></div><p class="question">${esc(q.question)}</p>${bars(q)}<div class="actions"><button class="btn danger" data-action="clear_question">Stemmen bij deze vraag wissen</button><button class="btn danger" data-action="clear_all">Alle stemmen wissen</button></div></section><section class="card"><h2>Individuele stemmen</h2><p class="muted">${state.totalVotes} stem${state.totalVotes === 1 ? '' : 'men'} bij deze vraag</p>${state.voters.length ? state.voters.map(voter => `<div class="voter"><strong>${esc(voter.name)}</strong><select class="select" data-voter="${esc(voter.id)}">${q.answers.map((answer,index)=>`<option value="${index}" ${index===voter.answerIndex?'selected':''}>${esc(answer.long)}</option>`).join('')}</select><button class="btn danger" data-action="delete_vote" data-voter="${esc(voter.id)}">Wis</button></div>`).join('') : '<div class="empty">Nog geen stemmen.</div>'}</section></div>`); document.querySelector('#questionSelect').addEventListener('change', event => action('select_question', {questionIndex:+event.target.value})); document.querySelectorAll('select[data-voter]').forEach(select => select.addEventListener('change', event => action('set_vote', {participantId:event.target.dataset.voter, answerIndex:+event.target.value}))); }
  function render() { if(!state) return; if(view === 'teacher') return renderTeacher(); if(view === 'presentation') return renderPresentation(); if(!state.me) return renderStudentName(); renderStudent(); }
  async function action(actionName, extra={}) { try { if(actionName === 'join') { const name = document.querySelector('#name').value.trim(); if(!name) return renderStudentName('Vul eerst je naam in.'); participantToken ||= createToken(); localStorage.setItem(tokenKey, participantToken); state = await call('join',{name,participantToken}); render(); return; } const answerIndex = document.activeElement?.dataset?.answer; const payload = {...extra, participantToken, teacherToken}; if(actionName === 'vote') payload.answerIndex = +answerIndex; state = await call(actionName,payload); render(); } catch(error) { alert(error.message); } }
  document.addEventListener('click', event => { const button = event.target.closest('[data-action]'); if(button) action(button.dataset.action); });
  async function init() { if(!uniqueId || !dataUrl) { app.innerHTML='<section class="card"><h2>Configuratie ontbreekt</h2><p>Gebruik een unique_id en data in de URL.</p></section>'; return; } try { if(view === 'teacher') { const config = await fetch(dataUrl,{cache:'no-store'}).then(response=>response.json()); state = await call('init',{config}); const claimed = await call('claim_teacher',{teacherToken}); teacherToken = claimed.teacherToken; localStorage.setItem(teacherKey,teacherToken); state = claimed; } else state = await stateGet(); render(); setInterval(async()=>{ try { state = await stateGet(); render(); } catch (_) {} },1000); } catch(error) { app.innerHTML = `<section class="card"><h2>Oeps</h2><p>${esc(error.message)}</p></section>`; } }
  init();
})();
